### ISSUE TITLE
Issue in booking appointment with counsellors

### ISSUE THREAD

**Issue by rajvinayak1809** [aleph-7/elysium#6]
![Screenshot 2024-04-04 153337](https://github.com/aleph-7/elysium/assets/129218965/b4a191e2-518c-40e2-80a5-4ecbb0b27965)
As shown in the image if a user books slot on same day (4th of April) his approval for appointment is showing as pending and according ton your algorithm it will update at 12 midnight then the slot can never be approved.

**Comment by whizdor** [comment]
The algorithm is only applicable for pre-booking in racquet sports. For a counsellor booking to be accepted, the counsellor needs to approve the booking from their dashboard, using their login and password. No algorithm has been applied here in order to conform to the way the Institute Counselling Service works, wherein a counsellor is supposed to maintain a personal relationship with the patients. This has been clearly stated in the Implementation Document and User Manual.

**Comment by RushikeshChary** [comment]
So, do counsellor get some kind of other user interface ?

**Comment by RushikeshChary** [comment]
I have tried to login as some counsellor / coach with the credentials, But its showing invalid credentials. How can I login as a coach if want to test that part.

**Comment by whizdor** [comment]
In order to login as a counsellor, you can use the pre-existing ids, 
username - iitk_counsellor_1
password - iitkcounsellor1

**Comment by rajvinayak1809** [comment]
![Screenshot 2024-04-04 161519](https://github.com/aleph-7/elysium/assets/129218965/dd6db827-5331-42fa-a9cd-12e570431cbd)
can you kindly provide the correct username and password for each cause the one in this table are not working

**Comment by whizdor** [comment]
# Passwords

## Coaches

```
Username :  iitk<sport_name>
Password :  iitk<sport_name>
```

## Other Instructors

```
Username :  iitk_<type>_<num>
Password :  iitk<type><num>
```

## Super User

```
Username :  superuser
Password :  superuser
```

## Sport Admin

```
Username :  admin_<sport_name>
Password :  admin<sport_name>
```
